# Generated by Django 4.0.3 on 2022-03-19 05:16

from django.db import migrations, models
import django.db.models.deletion
from competitions.models import Competency, CompetencyLevel


def initiate_competitions(apps, schema_editor):
    junior_level = CompetencyLevel.objects.create(name='Junior')
    middle_level = CompetencyLevel.objects.create(name='Middle')
    senior_level = CompetencyLevel.objects.create(name='Senior')

    Competency.objects.create(name='Junior Backend', level=junior_level)
    Competency.objects.create(name='Middle Backend', level=middle_level)
    Competency.objects.create(name='Senior Backend', level=senior_level)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='Not specified')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Not specified')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competencylevel')),
            ],
        ),
        migrations.RunPython(initiate_competitions)
    ]
