# Generated by Django 4.0.3 on 2022-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_skilltag_skilltoken_competency_skilltoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltag',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='skilltoken',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='competitions.skilltag'),
        ),
    ]
