# Generated by Django 4.0.3 on 2022-03-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0004_alter_skilltag_name_alter_skilltoken_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltoken',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
